# Generated by Django 5.2.4 on 2025-07-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_followers"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="followers",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="followers",
            name="unfollowed_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
