# Generated by Django 5.2.4 on 2025-07-07 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_followers_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unblocked_at', models.DateTimeField(default=None, null=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unmuted_at', models.DateTimeField(default=None, null=True)),
                ('muted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted', to=settings.AUTH_USER_MODEL)),
                ('muter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
