# Generated by Django 5.2.4 on 2025-07-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.CharField(default='sample title', max_length=100),
            preserve_default=False,
        ),
    ]
