# Generated by Django 5.2.4 on 2025-07-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threads", "0002_thread_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reply",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="thread",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
